### ISSUE TITLE
Can you release the package?

### ISSUE THREAD

**Issue by tianxinbaiyun** [arp242/zcache#3]
Your project is very good.Can you release the package?

**Comment by arp242** [comment]
There's a bunch of tagged releases; I don't know what you mean with "release the package"?

**Comment by tianxinbaiyun** [comment]
Publish package.

**Comment by arp242** [comment]
What does that mean?

**Comment by arp242** [comment]
Or let me put it this way: what problem are you facing?

**Comment by tianxinbaiyun** [comment]
I want to use your package, but the team requires a released package to use it.

**Comment by arp242** [comment]
Like I said, there are a bunch of tags, for v1 and v2. Beyond that a "releasing" or "publishing" a package doesn't really mean anything. Tagging a release is essentially "releasing a version".

You can see the tags in git, on GitHub, or on pkg.go.dev:

https://pkg.go.dev/zgo.at/zcache/v2
https://pkg.go.dev/zgo.at/zcache

**Comment by tianxinbaiyun** [comment]
Thank you.The released package is formal.The formal package is required by the development team.

**Comment by arp242** [comment]
> The released package is formal. The formal package is required by the development team.

I have no idea what that means either.
